-- See https://github.com/NvChad/minty
-- return {
--   "nvchad/minty",
--   dependencies = {
--     "nvchad/volt",
--   },
--   event = "VeryLazy",
--   opts = {
--     -- your configuration comes here
--     -- or leave it empty to use the default settings
--     -- refer to the configuration section below
--   },
-- }
return {}
