# vim:foldmethod=marker

##################################
#                                #
#   ._______________________.    #
#   |TFTFTFTFTFTFTFTFTFTFTFT|    #
#        |TFT|      |TFT|        #
#        |TFT|   .__|TFT|__.     #
#        |TFT|   |TFTFTFTFT|     #
#        |TFT|      |TFT|        #
#        |TFT|      |TFT|        #
#        |TFT|      |TFT|        #
#        |TFT|      |TFT|        #
#                                #
##################################

#: Configure zsh 
# Completion
autoload -Uz compinit
compinit
zstyle ':completion:*' menu select

# History
setopt no_share_history
unsetopt share_history


#: zinit bootstrap 
### Added by Zinit's installer
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
fi

source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zdharma-continuum/zinit-annex-as-monitor \
    zdharma-continuum/zinit-annex-bin-gem-node \
    zdharma-continuum/zinit-annex-patch-dl \
    zdharma-continuum/zinit-annex-rust
    #
### End of Zinit's installer chunk
#: 

#: Install some basic plugins with zinit 
zinit wait lucid light-mode for \
  atinit"zicompinit; zicdreplay" \
      zdharma-continuum/fast-syntax-highlighting \
      OMZP::colored-man-pages \
  atload"_zsh_autosuggest_start" \
      zsh-users/zsh-autosuggestions \
  atload"unalias grv" \
        OMZP::git \
  blockf atpull'zinit creinstall -q .' \
      zsh-users/zsh-completions

zinit wait lucid for \
        OMZL::git.zsh \
#: 

#: Configure prompt 
# required by most themes, so we just set it here
setopt promptsubst
# set temporary prompt until theme is loaded
PS1="[waiting for prompt] READY >"
# load actual prompt
# zinit wait'!' lucid for \
#     OMZL::prompt_info_functions.zsh \
#     OMZT::crunch
#     # OMZT::gnzh # <-- nice alternative theme
zinit ice compile'(pure|async).zsh' pick'async.zsh' src'pure.zsh'
zinit light sindresorhus/pure
#: 

#: LS colors 
zinit ice atclone"dircolors -b LS_COLORS > clrs.zsh" \
    atpull'%atclone' pick"clrs.zsh" nocompile'!' \
    atload'zstyle ":completion:*" list-colors “${(s.:.)LS_COLORS}”'
zinit light trapd00r/LS_COLORS
#: 

#: Configure fzf 
zinit pack"default+keys" for fzf

# [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
#: 

#: Configure asdf 
# . $(brew --prefix asdf)/libexec/asdf.sh
# # ASDF: read go version from go.mod / go.sum file
# export ASDF_GOLANG_MOD_VERSION_ENABLED=true
# #: 

#: Configure mise 
eval "$(mise activate zsh)"
eval "$(mise hook-env)"
#: 

#: Configure zoxide 
eval "$(zoxide init zsh)"
#: 

#: Configure arbitrary tooling 
# google-cloud-sdk setup
# source $(brew --prefix)/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc
# source $(brew --prefix)/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc
# 1Password / Glab
source $HOME/.config/op/plugins.sh
### MANAGED BY RANCHER DESKTOP START (DO NOT EDIT)
# export PATH="/Users/timo/.rd/bin:$PATH"
### MANAGED BY RANCHER DESKTOP END (DO NOT EDIT)
# Created by `pipx` on 2023-04-12 19:06:58
export PATH="$PATH:/Users/timo/.local/bin"
# ghcup
export PATH="$HOME/.ghcup/bin:$PATH"
#: 

#: Configure homebrew-managed tools (e.g. Add them to PATH) 
# curl
export PATH="/opt/homebrew/opt/curl/bin:$PATH"
# GNU sed
export PATH="/opt/homebrew/opt/gnu-sed/libexec/gnubin:$PATH"
export MANPATH="/opt/homebrew/opt/gnu-sed/libexec/gnuman:$MANPATH"
# GNU tools > macOS (e.g. ls, ...)
export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"
export MANPATH="/opt/homebrew/opt/coreutils/libexec/gnuman:$MANPATH"

# Workaround for Homebrew tmuxinator issue
# https://github.com/Homebrew/homebrew-core/issues/59484
# https://discourse.brew.sh/t/why-does-tmuxinator-sets-gem-home/7296
unset -v GEM_HOME

#: 

#: Kittens to PATH 
export PATH="$HOME/.config/kitty/kittens:$PATH"
#: 

#: Load aliases 
source $HOME/dotfiles/zsh/zsh_aliases
source $HOME/.zshrc_gitlab
#: 

#: Load generic completions 
source $HOME/.zsh_completions
#: 
